<a href="https://colab.research.google.com/github/tanmaykhanna07/python-for-data-science/blob/main/Numpy_Beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np


In [6]:
celcius_data = np.array([10,20,30,40,50,60])

farhenheit_data = (celcius_data * 1.8) + 32

print("Celcius data: ", celcius_data)
print("Farhenheit data: ", farhenheit_data)

Celcius data:  [10 20 30 40 50 60]
Farhenheit data:  [ 50.  68.  86. 104. 122. 140.]


In [7]:
sensor_data = np.array([
    [10, 12, 14, 15], # User 1
    [20, 22, 21, 23], # User 2
    [30, 31, 29, 32]  # User 3
])

print("The Matrix:\n", sensor_data)
print("\nShape of the data:", sensor_data.shape)

The Matrix:
 [[10 12 14 15]
 [20 22 21 23]
 [30 31 29 32]]

Shape of the data: (3, 4)


In [8]:
# 1. The Global Average (The entire 3x4 grid combined)
global_avg = np.mean(sensor_data)

# 2. Average per User (Calculating horizontally across rows -> axis=1)
user_avg = np.mean(sensor_data, axis=1)

# 3. Average per Day (Calculating vertically down columns -> axis=0)
day_avg = np.mean(sensor_data, axis=0)

print("Global Average:   ", global_avg)
print("Average per User: ", user_avg)
print("Average per Day:  ", day_avg)

Global Average:    21.583333333333332
Average per User:  [12.75 21.5  30.5 ]
Average per Day:   [20.         21.66666667 21.33333333 23.33333333]


In [10]:
# Rows = Core 1, Core 2, Core 3
# Columns = Test 1, Test 2, Test 3, Test 4, Test 5 (Temperatures in Celsius)
cpu_temps = np.array([
    [68, 71, 75, 82, 91],
    [70, 72, 78, 85, 95],
    [65, 68, 72, 79, 88]
])

sys_avg = np.mean(cpu_temps)
core_max = np.max(cpu_temps, axis = 1)
high_temp = cpu_temps[cpu_temps >= 85]

print("Average temperature of the cpu: ", sys_avg)
print("Maximum temperature of each core: ", core_max)
print("Temperatures above 85C: ", high_temp)

Average temperature of the cpu:  77.26666666666667
Maximum temperature of each core:  [91 95 88]
Temperatures above 85C:  [91 85 95 88]
